apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  selector:
    app: guestbook-ui
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: guestbook-ui
    protocol: TCP
  loadBalancerIP: 192.168.0.249
